[Mouse]
sensitivity = "0.5"

[Direction]
forward = 87 #W
back    = 83 #S
left    = 65 #A
right   = 68 #D

#for ***Key use a keyboard key, and for ***Btn a mouse button
#use 0 for unused key and 6 for unused mouse button
[Attack]
fireKey    = 0
fireBtn    = 0  #LMB
altFireKey = 0
altFireBtn = 1  #RMB
dashKey    = 32 #Space
dashBtn    = 6

# MOUSE BUTTON CODES
# Left Mouse Button       = 0
# Right Mouse Button      = 1
# Middle Mouse Button     = 2
# Lower Side Mouse Button = 3
# Lower Side Mouse Button = 4
# MOUSE_BUTTON_FORWARD    = 5 (these two are defined by raylib but no idea what they are)
# MOUSE_BUTTON_BACK       = 6

# KEYBOARD KEY CODES
# NULL = 0 (I think you can use this for unused binding)
#
# 0 = 48
# 1 = 49
# 2 = 50
# 3 = 51
# 4 = 52
# 5 = 53
# 6 = 54
# 7 = 55
# 8 = 56
# 9 = 57
#
# A = 65
# B = 66
# C = 67
# D = 68
# E = 69
# F = 70
# G = 71
# H = 72
# I = 73
# J = 74
# K = 75
# L = 76
# M = 77
# N = 78
# O = 79
# P = 80
# Q = 81
# R = 82
# S = 83
# T = 84
# U = 85
# V = 86
# W = 87
# X = 88
# Y = 89
# Z = 90
#
# Space         = 32
# Esc           = 256
# Enter         = 257
# Tab           = 258
# Backspace     = 259
# Insert        = 260
# Delete        = 261
#
# Right         = 262
# Left          = 263
# Down          = 264
# Up            = 265
#
# Page Up       = 266
# Page Down     = 267
# Home          = 268
# End           = 269
# Caps Lock     = 280
# Scroll Lock   = 281
# Num Lock      = 282
# Print Screen  = 283
# Pause         = 284
#
# F1            = 290
# F2            = 291
# F3            = 292
# F4            = 293
# F5            = 294
# F6            = 295
# F7            = 296
# F8            = 297
# F9            = 298
# F10           = 299
# F11           = 300
# F12           = 301
#
# Left Shift    = 340
# Left Ctrl     = 341
# Left Alt      = 342
# Right Shift   = 344
# Right Ctrl    = 345
# Right Alt     = 346
#
# Keypad 0      = 320
# Keypad 1      = 321
# Keypad 2      = 322
# Keypad 3      = 323
# Keypad 4      = 324
# Keypad 5      = 325
# Keypad 6      = 326
# Keypad 7      = 327
# Keypad 8      = 328
# Keypad 9      = 329
# Keypad .      = 330
# Keypad /      = 331
# Keypad *      = 332
# Keypad -      = 333
# Keypad +      = 334
# Keypad Enter  = 335
# Keypad =      = 336